### ISSUE TITLE
Cell with Integer value has an = sign

### ISSUE THREAD

**Issue by rnatarajan** [ZuInnoTe/spark-hadoopoffice-ds#21] opened 2019-03-19 04:31 UTC
I created a simple xlsx file with two values(1, A).
However when opening the Xlsx file, the value of Integer appears as =1 instead of 1.

`scala> val sRdd = sc.parallelize(Seq((1,"A")))
sRdd: org.apache.spark.rdd.RDD[(Int, String)] = ParallelCollectionRDD[0] at parallelize at <console>:24

scala> val df = spark.createDataFrame(sRdd)
df: org.apache.spark.sql.DataFrame = [_1: int, _2: string]

scala> df.repartition(1).write.format("org.zuinnote.spark.office.excel").option("write.locale.bcp47", "us").option("mapreduce.output.fileoutputformat.compress", "false").option("mapreduce.map.output.compress", "false").save("/tmp/somedir/1")
`

When i downloaded part-m-00000.xlsx and opened the file in Excel, the cell A1 has the value =1 and cell B1 has the value A

I am not sure why a column with integer type is written with value =1

I am unable to find an option in the wiki that explains this behavior.

**Comment by jornfranke** [comment] 2019-03-19 07:39
Thanks for reporting. I will look into it.

**Comment by jornfranke** [comment] 2019-03-19 07:43
Do you have some information on Spark version and Hadoop office version?

Did you open it with Excel again?

Are you sure that the displayed value is =1 or is it the formula =1?

**Comment by rnatarajan** [comment] 2019-03-19 14:06
I am using Spark - version 2.3.1.3.0.1.0-187, Scala - 2.11.8
I used com.github.zuinnote:spark-hadoopoffice-ds_2.11:1.2.4

The displayed value is 1. However when I click the cell to inspect the value, I see that the cell has the value =1.

<img width="285" alt="Screen Shot 2019-03-19 at 9 05 04 AM" src="https://user-images.githubusercontent.com/2908985/54612050-2b77e080-4a26-11e9-8b1b-5711eeb1a1ad.png">

<img width="252" alt="Screen Shot 2019-03-19 at 9 04 55 AM" src="https://user-images.githubusercontent.com/2908985/54612060-303c9480-4a26-11e9-8ba1-a15ea5411763.png">

I have attached snapshot for your reference.

**Comment by jornfranke** [comment] 2019-03-19 18:22
Thanks. This corresponds to a number in Excel, =1 is the formula to represent 1. It can be perfectly fine be used in other calculations.

Is there an issue to have a number  as a formula?

**Comment by rnatarajan** [comment] 2019-03-19 20:10
For a column with formulas, Excel throws Inconsistent Formula error. 
Thats what led me down this investigation.
A column with 3 rows 5, 1, 5 and Excel throws error for the value 1.
If the value had been numbers(5, 1, 5) in each cell instead of formula(=5, =1, =5) this error wouldn't have appeared. 

And in a excel with few thousand rows and bunch of columns, seeing this error pop up everywhere is distracting. 
Hence i wanted to see if there is a way to have Excel with numbers and fix the issue.

Excel with error:
<img width="367" alt="Screen Shot 2019-03-19 at 3 05 13 PM" src="https://user-images.githubusercontent.com/2908985/54638296-b671ce80-4a58-11e9-99b8-f7d498bcc2cf.png">

Same Excel with number instead of formula:
<img width="247" alt="Screen Shot 2019-03-19 at 3 06 52 PM" src="https://user-images.githubusercontent.com/2908985/54638306-c093cd00-4a58-11e9-9a13-7a72291ef8ae.png">

**Comment by jornfranke** [comment] 2019-03-19 23:17
I see - let me investigate. It could be that the formula is not evaluated in datasource.

**Comment by jornfranke** [comment] 2019-03-21 20:52
I will test a fix and if it works publish a new version 1.2.5 this weekend.

**Comment by jornfranke** [comment] 2019-03-24 17:27
Hmm somehow I fail to reproduce this issue exactly. Which Excel version are you using?

**Comment by jornfranke** [comment] 2019-03-24 17:38
I tried exactly to reproduce your case. However, it does not show me inconsistent formula. It could be related to the Excel version, but i can investigate once you told me your Excel version.

As a workaround, you can try to represent integers as String in the dataframe before saving them

**Comment by rnatarajan** [comment] 2019-03-26 16:30
Initially I was expressing integers as String and that was throwing another validation error.

I am using Microsoft Excel for Mac. Version 16.23

**Comment by jornfranke** [comment] 2019-03-26 19:20
That is really strange. I tested that version and I don’t see the validation error.
I will spend a couple of hours this week to see that I can reproduce it.
Thanks for your patience .

**Comment by rnatarajan** [comment] 2019-03-27 18:10
Thanks a lot.

I found that Excel had numerous Error checking options enabled.
And thus causing the warning. Can you please enable these settings and try to reproduce the issue.

Attached a snapshot of Error checking options.

<img width="595" alt="Screen Shot 2019-03-27 at 1 07 42 PM" src="https://user-images.githubusercontent.com/2908985/55101104-5fd84600-5091-11e9-91e6-06b491b74f8d.png">


Also I am attaching the code that I used to generate the xlsx file.

```
spark-shell --packages com.github.zuinnote:spark-hadoopoffice-ds_2.11:1.2.4 --exclude-packages org.apache.zookeeper:zookeeper,org.apache.hadoop:hadoop-yarn-server-test,org.apache.hadoop:*

scala> import org.apache.spark.sql._
scala> val sRdd = sc.parallelize(Seq((5,"A"), (1, "B"), (5, "C")))
scala> val df = spark.createDataFrame(sRdd)
scala> df.repartition(1).write.format("org.zuinnote.spark.office.excel").option("read.locale.bcp47", "us").option("mapreduce.output.fileoutputformat.compress", "false").option("mapreduce.map.output.compress", "false").save("/tmp/somepath1")
```

**Comment by jornfranke** [comment] 2019-03-27 22:49
I just quickly checked and those options were activated, nevertheless I will do a more intensive check. I checked Office 16.23 (Excel), but I will try and research some other options to reproduce what you see.  What I notice is that you try to insert tuples. This is not really supported by the data source (and I am not 100% on the behaviour, I will check). The data source basically supports the following:
* Simple Data types in a Data Frame (e.g. one based on Integer, Strings etc.). For instance, you can load a CSV/Avro/Parquet/ORC/etc. (without complex data types) as dataframe and then store it as Excel
* Inserting 5 tuples representing a cell, e.g. val sRdd = sc.parallelize(Seq(Seq("","","1","A1","Sheet1"),Seq("","This is a comment","2","A2","Sheet1"),Seq("","","3","A3","Sheet1"),Seq("","","A2+A3","B1","Sheet1"))).repartition(1)

**Comment by jornfranke** [comment] 2019-04-01 19:25
I can now reproduce the issue. However, in the Excel help it tells me that this could be perfectly fine (false warning). The warning is shown if the Excel formula does not show a similar pattern as the previous one, e.g.
If you want to multiply column A with B and you have the formulas
A1*B1, A2*B2, A3*B3 etc.
If A4*B2 is the next formula after A3*B3 then Excel shows a warning because it expects A4*B4 

I will see if this issue can be omitted somehow programatically

**Comment by jornfranke** [comment] 2019-04-01 19:27
As a workaround see my previous comment (using 5 tuples)

**Comment by rnatarajan** [comment] 2019-04-01 19:58
Thanks for the quick response.

I will have a look at the 5 tuples example.

I shared the scala code as an example.
I am using Java/Spark integration to write about a million rows.
And the million rows throw the warning sign making the excel undesirable to follow.
Since the INT values are not formulae, If the = sign can be omitted for INT that will be ideal.

Meanwhile, I will also experiment with the example and will update this thread.

**Comment by jornfranke** [comment] 2019-04-01 22:01
I believe it can be omitted. I will just check with the Apache POI team if we can somehow sync this with Apache POI 4.1, but if they take too long then I will do an earlier release.

**Comment by rnatarajan** [comment] 2019-04-02 18:39
Sounds good to me.

**Comment by jornfranke** [comment] 2019-04-05 22:33
It is fixed in master. It looks on the POI mailing list that we soon have 4.1. If it is not there by mid of next week then I will create an in-between release on Wednesday

**Comment by rnatarajan** [comment] 2019-04-08 15:07
Thanks a lot. I will test the changes as soon as the version is available.

**Comment by jornfranke** [comment] 2019-04-09 20:12
they released it today. I give it a go tomorrow

**Comment by jornfranke** [comment] 2019-04-10 20:41
Unfortunately, it will take longer. If you store them directly as general cell then Excel complains that the type should be stored as text... This will require more rework (and has also some limitations due to the strict typing of dataframes) and more time.
For now, you can hide the issue hints, it does not look to me that they have a negative impact on Excel in your case

**Comment by rnatarajan** [comment] 2019-05-17 15:55
Hi @jornfranke Is there an update on this fix ?

**Comment by jornfranke** [comment] 2019-05-17 16:08
Hi,

Even with just numbers you have this notification in Excel. I tried in Excel (without hadoopoffice involvement) a different set of numbers and they were also highlighted.
I recommend to deactivate the highlight of warnings because some warnings are related to very specific use cases and may not make sense for everyone.

Best regards

**Closed as completed** 2019-11-02 17:16 UTC
