### ISSUE TITLE
Support for Spark 2.1.0

### ISSUE THREAD

**Issue by jkommeren** [ZuInnoTe/spark-hadoopoffice-ds#2] opened 2017-05-18 08:02 UTC
Using version 1.0.2

Currently when I try to use the hadoopoffice-ds package to write an .xlsx file, for example by using your own example "hadoopoffice\examples\scala-spark2-excel-out-ds" on my Spark 2.1.0 cluster, I get an error stating a method of the abstract OutputWriterFactory class can not be found on the OutputWriterFactory it's trying to use, when it calls the df.write method

Stacktrace:
```

Caused by: java.lang.AbstractMethodError: org.apache.spark.sql.execution.datasources.OutputWriterFactory.getFileExtension(Lorg/apache/hadoop/mapreduce/TaskAttemptContext;)Ljava/lang/String;
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$SingleDirectoryWriteTask.<init>(FileFormatWriter.scala:232)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.org$apache$spark$sql$execution$datasources$FileFormatWriter$$executeTask(FileFormatWriter.scala:182)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$write$1$$anonfun$3.apply(FileFormatWriter.scala:129)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$write$1$$anonfun$3.apply(FileFormatWriter.scala:128)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:99)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:322)
	... 3 more
```

My own example code that's failing with Spark 2.1.0

```
import spark.implicits._
val sqlContext=new SQLContext(sc)
import sqlContext.implicits._

val sRdd = sc.parallelize(Seq("1","2","3","4","5")).repartition(1)
val df= sRdd.toDF()
try {
    df.write.format("org.zuinnote.spark.office.excel").mode(SaveMode.Overwrite).save("/user/spark/output/")
} catch {
    case e: Exception => {
         val sw = new StringWriter
       e.printStackTrace(new PrintWriter(sw))
        println(sw.toString)
    } 
}
```

It works fine when I use Spark 2.0.2 however.

I did some research:

It's correct that Spark 2.1.0 adds a method to the abstract OutputWriterFactory:
`org.apache.spark.sql.execution.datasources.OutputWriterFactory#def getFileExtension(context: TaskAttemptContext): String`
I saw a similar issue when the databricks-avro dependency was used, which had a similar issue when version 3.1.0 was used, 3.2.0 fixed this.
Link describing the issue and fix: https://github.com/databricks/spark-redshift/issues/315 

This is not the dependency you were using however (apache's own version), so I think it's a dependency that's using it?

All that neads to be done is add an override for the method returning a fileextension.

I can see what else I can find in the meantime, but I'm having issues setting up debugging from IntelliJ with the Spark cluster (HDInsight), so have a hard time figuring out where it's going wrong exactly. Maybe you can check it out too?

Appreciate your work by the way!

**Comment by jornfranke** [comment] 2017-05-18 19:35
Hi,

thank you for your detailed report! In fact, you were right there is a change in the WriterFactory in Spark 2.1.0. I needed to add getFileExtension and newInstance. I confirmed with the integrationTests that it already work. Before I release it, I need to do another test with a cluster. 
It should be soon available.

Best regards

**Comment by jkommeren** [comment] 2017-05-18 19:40
Hey Jörn!

Nice! Thanks for your swift action! :-D

Really looking forward to the next release!

Regards,

Joris

**Comment by jkommeren** [comment] 2017-05-19 06:21
If you want I can help test it :-) 

Also I have some ideas for improvements / new functionality, are you interested?

Regards,

Joris

**Comment by jornfranke** [comment] 2017-05-19 07:06
Hallo,

Yes all this is welcome! 

Wrt to improvements/enhancements: if they are not only related to datasource functionality itself, but the overall functionality please register them under the underlying HadoopOffice library https://github.com/zuinnote/hadoopoffice

There, you find already some proposals for improvements.

Thank you a lot for your support.

**Comment by jkommeren** [comment] 2017-05-19 14:22
I can confirm it works now when built from source on my Spark 2.1.0 HDInsight cluster 👍 

I built the updated fileformat in the hadoopoffice repo to a separate jar, put it in my ivy2 cache, and spark-hadoopoffice-ds built successfully. Then ran a test on my spark cluster. Xlsx output file was valid!

Good job!

**Comment by jornfranke** [comment] 2017-05-19 14:25
Great thx for the feedback. It should be released within the next days.

**Comment by jornfranke** [comment] 2017-05-19 21:37
Just released the fix. It is available on Maven Central and Spark-packages.
I close this issue, because you and me tested. Thank you again for the great support!

**Closed as completed by jornfranke** 2017-05-19 21:37 UTC
